INSERT INTO products (id, name, brand, website, ig_post, notes) VALUES
('Pan dulce vegano', 'Oralí', 'https://www.pastasorali.com/', 'https://www.instagram.com/p/C1A60CNrXOf/'),
('Not Burger Quick', 'NotCo', 'https://notco.com/ar/', 'https://www.instagram.com/p/C05KbUGLGw5/'),
('Pasas de uva con chocolate', 'Día', 'https://diaonline.supermercadosdia.com.ar/', 'https://www.instagram.com/p/C0pwgOwLhxY/'),
('Maní con chocolate', 'Día', 'https://diaonline.supermercadosdia.com.ar/', 'https://www.instagram.com/p/C0cs7Jpradp/'),
('Caramero masticable ácido', 'Xtreme', 'https://diaonline.supermercadosdia.com.ar/', 'https://www.instagram.com/p/C0VMbQ2L1Ie/'),
('Untable clásico 100% Vegetal', 'La Serenísima', 'https://www.laserenisima.com.ar/', 'https://www.instagram.com/p/C0C3CJjv5r5/'),
('Milanesas grandes de soja sabor fugazzeta', 'Lucchetti', 'https://www.mamalucchetti.com.ar/', 'https://www.instagram.com/p/CzxCoSgLW-_/'),
('Maní con chocolate', 'Chocolates Bariloche', 'https://chbariloche.com.ar/es/', 'https://www.instagram.com/p/CzpUWZirma5/'),
('Galletitas con salvado', 'Bagley', 'https://bagley.com.ar/default.aspx', 'https://www.instagram.com/p/CzfGUu5Lmne/'),
('Jugo en polvo sabor manzana', 'BC La Campagnola', 'https://www.arcor.com/es/marca/bc-la-campagnola', 'https://www.instagram.com/p/CzFTF3bLOK8/'),
('Mezcla esto no es huevo', 'ENE foods', 'https://www.enefoods.com/', 'https://www.instagram.com/p/Cy69wysLiPh/'),
('Shampoo para cabellos con frizz HYDRA LISS', 'Garnier', 'https://www.garnier.com.ar/', 'https://www.instagram.com/p/Cy18cV5L5LD/'),
('Not Chicken Crispy', 'NotCo', 'https://notco.com/ar/', 'https://www.instagram.com/p/CyhNTsortXr/'),
('Protector solar factor 50', 'Villeneuve', 'https://vnlatam.com/', 'https://www.instagram.com/p/CyZXW9fPeT7/'),
('Falafel', 'Otro Viaje', 'https://www.otroviaje.com.ar/', 'https://www.instagram.com/p/CyR14kOrk02/'),
('Gnocchis con papa', 'Cuisine & Co', 'https://www.otroviaje.com.ar/', 'https://www.instagram.com/p/CyR14kOrk02/'),
